with-expecter: true
dir: internal/mocks
outpkg: mocks
packages:
  github.com/zjrosen/xorchestrator/internal/beads:
    interfaces:
      BeadsClient:
      BeadsExecutor:
  github.com/zjrosen/xorchestrator/internal/bql:
    interfaces:
      BQLExecutor:
  github.com/zjrosen/xorchestrator/internal/cachemanager:
    interfaces:
      CacheManager:
  github.com/zjrosen/xorchestrator/internal/mode/shared:
    interfaces:
      Clock:
      Clipboard:
  github.com/zjrosen/xorchestrator/internal/orchestration/client:
    interfaces:
      AgentProvider:
      HeadlessClient:
      HeadlessProcess:
  github.com/zjrosen/xorchestrator/internal/git:
    interfaces:
      GitExecutor:
  github.com/zjrosen/xorchestrator/internal/sound:
    interfaces:
      SoundService:
